namespace: space2study-prod

image:
  registry: "456631682423.dkr.ecr.eu-central-1.amazonaws.com"

frontend:
  replicas: 2
  image:
    tag: latest
backend:
  replicas: 2
  image:
    tag: latest

mongodb:
  replicas: 3

externalSecrets:
  appSecretsName: space2study-app-secrets-prod
