Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "database" do |db|
    db.vm.hostname = "space-db"
    db.vm.network "private_network", ip: "192.168.56.12"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end

  config.vm.define "frontend" do |frontend|
    frontend.vm.hostname = "space-frontend"
    frontend.vm.network "private_network", ip: "192.168.56.10"
    frontend.vm.network "forwarded_port", guest: 3000, host: 3000
    frontend.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end

  config.vm.define "backend" do |backend|
    backend.vm.hostname = "space-backend"
    backend.vm.network "private_network", ip: "192.168.56.11"
    backend.vm.network "forwarded_port", guest: 8080, host: 8080
    backend.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end
end