server {
    listen 8080;
    server_name localhost;

    # Writable temp locations for unprivileged user
    client_body_temp_path /tmp/client_temp 1 2;
    proxy_temp_path       /tmp/proxy_temp 1 2;
    fastcgi_temp_path     /tmp/fastcgi_temp 1 2;
    uwsgi_temp_path       /tmp/uwsgi_temp 1 2;
    scgi_temp_path        /tmp/scgi_temp 1 2;

    # Static UI Files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}