apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "space2study.fullname" . }}-ingress
  labels:
    {{- include "space2study.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - {{- if .Values.global.domain }}
      host: {{ .Values.global.domain | quote }}
      {{- end }}
      http:
        paths:
          # Route all API traffic to the backend service
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "space2study.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          # Route all remaining web traffic to the frontend UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "space2study.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}