apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels: { app: backend }
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      serviceAccountName: backend
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector: { matchLabels: { app: backend } }
      containers:
        - name: backend
          image: "{{ .Values.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.port }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            {{- range $k, $v := .Values.backend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: MONGODB_URL
              value: "mongodb://$(DB_USERNAME):$(DB_PASSWORD)@{{ range $i := until (int .Values.mongodb.replicas) }}{{ if $i }},{{ end }}mongodb-{{ $i }}.mongodb-headless.{{ $.Values.namespace }}.svc.cluster.local:{{ $.Values.mongodb.port }}{{ end }}/space2study?replicaSet=rs0&authSource=admin"
          envFrom:
            - secretRef: { name: backend-app-secrets }
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tmp
          emptyDir: {}