# helm install ingress-nginx ingress-nginx/ingress-nginx \
#   -n ingress-nginx --create-namespace -f cluster-addons/ingress-nginx-values.yaml

controller:
  kind: DaemonSet
  hostNetwork: false
  hostPort:
    enabled: true
  service:
    enabled: false
  admissionWebhooks:
    enabled: true
  resources:
    requests: { cpu: 50m, memory: 90Mi }
    limits: { cpu: 200m, memory: 250Mi }
  config:
    use-forwarded-headers: "true"
    ssl-redirect: "true"