apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mongodb-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGO_INITDB_ROOT_USERNAME: "{{ `{{ .DB_USERNAME }}` }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ `{{ .DB_PASSWORD }}` }}"
        keyfile: "{{ `{{ .MONGO_KEYFILE }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.appSecretsName }}
