apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    {{- include "space2study.labels" . | nindent 4 }}
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  clusterIP: None
  selector:
    app: mongodb