Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.network "forwarded_port", guest: 3000, host: 3000, id: "frontend"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, id: "backend"

  config.vm.synced_folder "../../../", "/workspace"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "Space2Study-Docker-Node"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../Configuration Management/ansible/docker-site.yml"
    ansible.inventory_path = "../../Configuration Management/ansible/inventories/local/hosts.ini"
    
    ansible.extra_vars = {
      host_ip: "192.168.56.20"
    }

 end
end
