apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space2study
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.domain | default "space2study.local" | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.domain | default "space2study.local" | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port: { number: {{ .Values.backend.port }} }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: { number: {{ .Values.frontend.port }} }
