apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels: { app: frontend }
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      serviceAccountName: frontend
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile: { type: RuntimeDefault }
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector: { matchLabels: { app: frontend } }
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.port }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-run
              mountPath: /var/run
            - name: var-cache
              mountPath: /var/cache/nginx
          livenessProbe:
            httpGet: { path: /, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet: { path: /, port: {{ .Values.frontend.port }} }
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - { name: tmp, emptyDir: {} }
        - { name: var-run, emptyDir: {} }
        - { name: var-cache, emptyDir: {} }