apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels: { app: frontend }
