apiVersion: v1
kind: Secret
metadata:
  name: {{ include "space2study.fullname" . }}-secrets
  labels:
    {{- include "space2study.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  JWT_RESET_SECRET: {{ .Values.secrets.jwtResetSecret | quote }}
  JWT_CONFIRM_SECRET: {{ .Values.secrets.jwtConfirmSecret | quote }}
  MAIL_USER: {{ .Values.secrets.mailUser | quote }}
  MAIL_PASS: {{ .Values.secrets.mailPass | quote }}
  GMAIL_CLIENT_ID: {{ .Values.secrets.gmailClientId | quote }}
  GMAIL_CLIENT_SECRET: {{ .Values.secrets.gmailClientSecret | quote }}
  GMAIL_REFRESH_TOKEN: {{ .Values.secrets.gmailRefreshToken | quote }}
  GMAIL_REDIRECT_URI: {{ .Values.secrets.gmailRedirectUri | quote }}