---
# Non-sensitive backend variables
repo: "https://github.com/Mredict/Space2Study-Mredict.git"
server_port: "8080"
server_url: "http://192.168.56.11:8080"
cookie_domain: "192.168.56.10"
client_url: "http://192.168.56.10:3000"
mongodb_url: "mongodb://192.168.56.12:27017/space2study"
jwt_access_expires_in: "1h"
jwt_refresh_expires_in: "7d"
jwt_reset_expires_in: "1h"
jwt_confirm_expires_in: "1h"