---
- name: Base configuration to all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Configure Database
  hosts: database
  become: true
  roles:
    - database

- name: Configure Backend
  hosts: backend
  become: true
  roles:
    - backend

- name: Configure Frontend
  hosts: frontend
  become: true
  roles:
    - frontend
